// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUQxYDjk2tOYwnMsrLs6jmCYmJJsQWtqQ',
    appId: '1:349865961733:web:a688556d1fea4779202f6c',
    messagingSenderId: '349865961733',
    projectId: 'cit-car-wash',
    authDomain: 'cit-car-wash.firebaseapp.com',
    storageBucket: 'cit-car-wash.appspot.com',
    measurementId: 'G-F7H8QB011C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyxdHLi7XBH_P7B8sQe0DY6fJpnflCmA8',
    appId: '1:349865961733:android:b07c2e888fa29245202f6c',
    messagingSenderId: '349865961733',
    projectId: 'cit-car-wash',
    storageBucket: 'cit-car-wash.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGci3OBq5z12OISDGSryn79fPCx7yhBy4',
    appId: '1:349865961733:ios:9123c2215970fcb6202f6c',
    messagingSenderId: '349865961733',
    projectId: 'cit-car-wash',
    storageBucket: 'cit-car-wash.appspot.com',
    iosBundleId: 'com.citgroupvn.carwash.mobile.citgroupvnCarwash',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGci3OBq5z12OISDGSryn79fPCx7yhBy4',
    appId: '1:349865961733:ios:5ce457f1e63d5b35202f6c',
    messagingSenderId: '349865961733',
    projectId: 'cit-car-wash',
    storageBucket: 'cit-car-wash.appspot.com',
    iosBundleId: 'com.citgroupvn.carwash.mobile.citgroupvnCarwash.RunnerTests',
  );
}
